import { Footer } from "@/components/Footer";
import StyledComponentsRegistry from "@/lib/registry";
import { GlobalStyle } from "@/styles/global";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Hackathon",
  description: "Generated by o hack e o thon",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <StyledComponentsRegistry>
          <GlobalStyle />
          {children}
          <Footer /> {/* Adicionando o Footer aqui */}
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
